# -*- coding: utf-8 -*-

# Copyright (c) 2009 Peter Schuller <peter.schuller@infidyne.com>

from __future__ import absolute_import
from __future__ import with_statement

import errno
import os.path
import unittest

import shastity.metadata as metadata

class MetaDataTests(unittest.TestCase):
    def setUp(self):
        pass

    def test_write_protection(self):
        md = metadata.FileMetaData()
        
        def assign_test():
            md.user_write = False
        self.assertRaises(AssertionError, assign_test)

    def test_init_assignment(self):
        for propname in metadata.FileMetaData.propnames:
            for boolval in [ True, False ]:
                propdic = dict()
                propdic[propname] = boolval

                self.assertEqual(getattr(metadata.FileMetaData(props=propdic), propname), boolval)

    def test_other_copy(self):
        for propname in metadata.FileMetaData.propnames:
            for boolval in [ True, False ]:
                propdic = dict()
                propdic[propname] = boolval

                self.assertEqual(getattr(metadata.FileMetaData(other=metadata.FileMetaData(props=propdic)), propname), boolval)

    def test_dict_iface(self):
        for propname in metadata.FileMetaData.propnames:
            for boolval in [ True, False ]:
                propdic = dict()
                propdic[propname] = boolval

                self.assertEqual(metadata.FileMetaData(props=propdic)[propname], boolval)

    def test_mode_strings(self):
        # common base test
        self.assertEqual(metadata.mode_to_str(dict(is_directory=True,
                                                   is_regular=False,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=True,
                                                   user_write=True,
                                                   user_execute=True,
                                                   group_read=True,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         'drwxr-xr-x')
        # symlinks are special
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=False,
                                                   is_symlink=True,
                                                   is_block_device=False,
                                                   is_character_device=False)),
                         'lrwxr-xr-x')
        # misc permutations, one character at a time
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=True,
                                                   user_write=True,
                                                   user_execute=True,
                                                   group_read=True,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '-rwxr-xr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=False,
                                                   is_symlink=False,
                                                   is_block_device=True,
                                                   is_character_device=False,
                                                   user_read=True,
                                                   user_write=True,
                                                   user_execute=True,
                                                   group_read=True,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         'brwxr-xr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=False,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=True,
                                                   user_read=True,
                                                   user_write=True,
                                                   user_execute=True,
                                                   group_read=True,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         'crwxr-xr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=True,
                                                   user_execute=True,
                                                   group_read=True,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '--wxr-xr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=True,
                                                   group_read=True,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '---xr-xr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=True,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '----r-xr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=True,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=True,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '---Sr-xr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=True,
                                                   group_read=True,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=True,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '---sr-xr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '------xr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=True,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '-----wxr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=False,
                                                   group_execute=False,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '-------r-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=False,
                                                   group_execute=False,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=True,
                                                   is_sticky=False)),
                         '------Sr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=False,
                                                   group_execute=True,
                                                   other_read=True,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=True,
                                                   is_sticky=False)),
                         '------sr-x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=False,
                                                   group_execute=False,
                                                   other_read=False,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '---------x')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=False,
                                                   group_execute=False,
                                                   other_read=False,
                                                   other_write=True,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '--------wx')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=False,
                                                   group_execute=False,
                                                   other_read=False,
                                                   other_write=False,
                                                   other_execute=False,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=False)),
                         '----------')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=False,
                                                   group_execute=False,
                                                   other_read=False,
                                                   other_write=False,
                                                   other_execute=False,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=True)),
                         '---------T')
        self.assertEqual(metadata.mode_to_str(dict(is_directory=False,
                                                   is_regular=True,
                                                   is_symlink=False,
                                                   is_block_device=False,
                                                   is_character_device=False,
                                                   user_read=False,
                                                   user_write=False,
                                                   user_execute=False,
                                                   group_read=False,
                                                   group_write=False,
                                                   group_execute=False,
                                                   other_read=False,
                                                   other_write=False,
                                                   other_execute=True,
                                                   is_setuid=False,
                                                   is_setgid=False,
                                                   is_sticky=True)),
                         '---------t')
        

if __name__ == "__main__":
    unittest.main()
